[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{access = "read", path="./"}]

solc = "0.8.28"
optimizer = true
optimizer_runs = 100
via_ir = true

[dependencies]
"@openzeppelin-contracts" = "5.5.0-rc.1"
"@openzeppelin-contracts-upgradeable" = "5.5.0-rc.1"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
rhs_testnet = "${RHS_TESTNET_RPC_URL}"
rhs = "${RHS_RPC_URL}"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[soldeer]
remappings_generate = true
remappings_regenerate = true
remappings_version = true
remappings_prefix = ""
remappings_location = "txt"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
